
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-service-monitor
  namespace: fastapi
spec:
  selector:
    matchLabels:
      app: fastapi
  endpoints:
  - port: http
    interval: 30s
