services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fastapi-dev
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./app:/app
      - ./sqlite3:/app/sqlite3
      - ./data:/data
      - ./tests:/tests  # ✅ 추가
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

