version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fastapi-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app # 코드 핫리로드용
      - ./data:/data # ✅ 로컬에서 SQLite DB 확인 가능
    entrypoint: [ "/app/sqlite3/docker-entrypoint.sh" ]
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

volumes:
  db-data:
