FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl sqlite3 && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g newman && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x /app/sqlite3/docker-entrypoint.sh

EXPOSE 8000
