version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fastapi-dev     # added container name
    ports:
      - "${APP_PORT:-1015}:8000"     # mapping 1015
    volumes:
      - ./src:/src/app               # ✅ Python 소스코드
      - ./data:/src/data             # ✅ DB 파일 (SQLite)
      - ./sqlite3:/src/sqlite3        # ✅ DB 초기화 스크립트
      - ./tests:/src/tests            # ✅ 테스트 코드
      - ./htmlcov:/src/htmlcov        # ✅ 커버리지 결과
    env_file:
      - .env
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped           # ✅ 서버 재부팅 후 자동 복구

