apiVersion: apps/v2
kind: Deployment
metadata:
  name: fastapi-green
  labels:
    app: fastapi
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
      version: green
  template:
    metadata:
      labels:
        app: fastapi
        version: green
    spec:
      containers:
      - name: fastapi
        image: terrnabin/fastapi_app:v2
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
