
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fastapi-policy
spec:
  podSelector:
    matchLabels:
      app: fastapi
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
