apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
      version: blue
  template:
    metadata:
      labels:
        app: fastapi
        version: blue
    spec:
      containers:
        - name: fastapi
          image: sungbin/fastapi-app:v1
          volumeMounts:
            - name: db-volume
              mountPath: /data
          ports:
            - containerPort: 8000
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: sqlite-pvc