apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
data:
  01_create_users_table.sql: |
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT UNIQUE NOT NULL
    );
    INSERT INTO users (name, email) VALUES ('Alice', 'alice@example.com');