apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: fastapi

resources:
  # 스토리지 (PV, PVC)
  - config/fastapi-pv.yaml
  - config/fastapi-pvc.yaml

  # 설정 (ConfigMap, Secret)
  - config/fastapi-configmap.yaml
  - config/fastapi-secret.yaml

  # 서비스 (fastapi용)
  - service/fastapi-active.yaml
  - service/fastapi-preview.yaml

  # 롤아웃 (배포)
  - rollout/fastapi-rollout.yaml

# 선택적으로 나중에 추가할 것 (모니터링, HPA, 네트워크 정책, 인그레스)
#  - monitoring/fastapi-service-monitor.yaml
#  - hpa/fastapi-hpa.yaml
#  - ingress/fastapi-ingress.yaml
#  - policy/fastapi-networkpolicy.yaml

