apiVersion: v1
kind: Namespace
metadata:
  name: argo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-workflow-controller
  namespace: argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-workflow-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argo-workflow-controller
    spec:
      containers:
      - name: argo-workflow
        image: quay.io/argoproj/workflow-controller:v3.5.7
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: argo-workflows-server
  namespace: argo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32082
  selector:
    app.kubernetes.io/name: argo-workflow-controller