apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-rollouts-config-rolebinding
  namespace: argo-rollouts
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo-rollouts
roleRef:
  kind: Role
  name: argo-rollouts-config-role
  apiGroup: rbac.authorization.k8s.io
