# k8s/argo/argo-rollouts-role-default.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-rollouts-role
  namespace: default   # <-- 여기 default임
rules:
- apiGroups: ["argoproj.io"]
  resources: ["rollouts", "rollouts/status", "experiments", "analysisruns", "analysistemplates", "clusteranalysistemplates"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-rollouts-rolebinding
  namespace: default   # <-- 여기 default임
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo-rollouts   # <-- argo-rollouts 네임스페이스의 default 서비스어카운트
roleRef:
  kind: Role
  name: argo-rollouts-role
  apiGroup: rbac.authorization.k8s.io

