apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-rollouts-controller
  namespace: argo-rollouts
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-rollouts-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argo-rollouts-controller
    spec:
      containers:
      - name: argo-rollouts
        image: quay.io/argoproj/argo-rollouts:v1.6.5
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: argo-rollouts-server
  namespace: argo-rollouts
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32081
  selector:
    app.kubernetes.io/name: argo-rollouts-controller