apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-config
  namespace: argo-rollouts
data:
  config: |
    {
      "rolloutConditions": [
        {
          "type": "Progressing",
          "status": "True",
          "reason": "NewReplicaSetAvailable"
        }
      ],
      "analysisTemplates": []
    }
