# k8s/argo/argo-rollouts-rbac.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo-rollouts
  name: argo-rollouts-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-rollouts-binding
  namespace: argo-rollouts
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo-rollouts
roleRef:
  kind: Role
  name: argo-rollouts-role
  apiGroup: rbac.authorization.k8s.io
