apiVersion: v1
kind: Service
metadata:
  name: fastapi-preview
  namespace: default
spec:
  selector:
    app: fastapi
    track: canary   # 🔥 수정: stable ➔ canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort

