apiVersion: v1
kind: Service
metadata:
  name: fastapi-active
  namespace: default
spec:
  selector:
    app: fastapi
    track: stable
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort

