apiVersion: v1
kind: Service
metadata:
  name: fastapi-active
spec:
  type: NodePort   # <-- LoadBalancer 대신 NodePort
  selector:
    app: fastapi
    track: stable
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080    # 사용할 포트 지정 (30000 ~ 32767 사이 아무거나 가능)
