apiVersion: v1
kind: Service
metadata:
  name: nginx-preview
  namespace: default
spec:
  selector:
    app: nginx
    track: stable   # 🔥 수정: stable ➔ canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort

