apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: default
spec:
  selector:
    app: current
    version: blue   # ← 최초 배포 시엔 blue로 시작
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
