# .github/workflows/argocd.yml
name: CI/CD to ArgoCD

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Install yq
      run: |
        sudo apt-get update
        sudo apt-get install -y yq

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        IMAGE=terrnabin/fastapi_app
        TAG=${{ github.sha }}
        docker build --build-arg VERSION=$TAG -t $IMAGE:$TAG .
        docker push $IMAGE:$TAG

    - name: Bump image in K8s manifests
      run: |
        TAG=${{ github.sha }}
        yq e -i ".spec.template.spec.containers[0].image = \"terrnabin/fastapi_app:$TAG\"" k8s/rollout/fastapi-rollout.yaml
        git config user.name  "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add k8s/rollout/fastapi-rollout.yaml
        git commit -m "ci: bump image to $TAG"
        git pull --rebase origin main
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up kubectl
      id: k8s
      uses: azure/setup-kubectl@v3
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Verify K8s connectivity
      env:
        KUBECONFIG: ${{ steps.k8s.outputs.kubeconfig }}
      run: |
        kubectl get nodes

    - name: Sync ArgoCD Application
      env:
        KUBECONFIG:    ${{ steps.k8s.outputs.kubeconfig }}
        ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
        ARGOCD_TOKEN:  ${{ secrets.ARGOCD_TOKEN }}
      run: |
        # download argocd CLI
        curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd

        # login using token with port-forward
        ./argocd login $ARGOCD_SERVER \
          --grpc-web \
          --auth-token $ARGOCD_TOKEN \
          --port-forward \
          --port-forward-namespace argocd \
          --insecure

        # sync and wait
        ./argocd app sync fastapi-app
        ./argocd app wait fastapi-app --health
